modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="demonica_angellica"
version="1.0.0"
displayName="Demonica Angellica"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Pete, MCreator"

[[dependencies.demonica_angellica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




